### ISSUE TITLE
Replace var with let/const (#181) error

### ISSUE THREAD

**Issue by kevinetore** [foreversd/forever-monitor#184]
PR #181 seems to give the following error:

```js
/usr/lib/node_modules/forever/node_modules/forever-monitor/lib/forever-monitor/monitor.js:38
let execPath = process.execPath;
^^^^^^^^
SyntaxError: Unexpected identifier
at Module._compile (module.js:439:25)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.<anonymous> (/usr/lib/node_modules/forever/node_modules/forever-monitor/lib/index.js:14:19)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32).
```

**Comment by kibertoad** [comment]
What Node version are you using, and how can I reproduce?

**Comment by kevinetore** [comment]
@kibertoad Our app servers are using an older version of Node `v6.17.1`, which could be the reason why the newer syntax is failing on our machine. For now, I've downgraded the `forever` version to [`1.0.0`](https://www.npmjs.com/package/forever). Again, I assume that our Node version is the reason behind all this, so this issue can be marked as closed.

**Comment by kibertoad** [comment]
@kevinetore We are actually running CI on 6.17.1 and it seems to be working just fine. Can you double-check that this is the version that is actually used? What do you get when running `node --version`?
