### ISSUE TITLE
Splitting the command by spaces renders an invalid/broken command

### ISSUE THREAD

**Issue by kessler** [foreversd/forever-monitor#35]
This fails, at least on my windows machine:

```
var forever = require('forever-monitor');
var child = forever.start('server.js');
```

the result was:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)
```

Debugging the problem yielded the following (excerpt from monitor.js - trySpawn()):

```
Monitor.prototype.trySpawn = function () {
  var command, cmdarr, stats, args;

  if (/[^\w]node$/.test(this.command) && this.checkFile && !this.childExists) {
    try {
      stats = fs.statSync(this.args[0]);
      this.childExists = true;
    }
    catch (ex) {
      return false;
    }
  }

  this.spawnWith.cwd = this.cwd || this.spawnWith.cwd;
  this.spawnWith.env = this._getEnv();

  if (this.stdio) {
    this.spawnWith.stdio = this.stdio;
  }
```

**_at this point, command === "C:\Program Files\nodejs\node.exe"**_

```
  cmdarr  = this.command.trim().split(/\s+/);
  command = this.command; 
```

**_now its "C:\Program"**_

```
  args    = this.args;

  if (cmdarr.length > 1) {
    command = cmdarr[0];
    args = cmdarr.slice(1).concat(this.args);
  }

  if (this.fork) {
    if (!this.stdio) {
      this.spawnWith.stdio = [ 'pipe', 'pipe', 'pipe', 'ipc' ];
    }
    return spawn(command, args, this.spawnWith);
  }

  return spawn(command, args, this.spawnWith);
};
```

I'm not entirely sure if it is something that needs fixing (would love a comment on that).

In the meanwhile my workaround was to start with the "command" option:

```
var forever = require('forever-monitor');
var child = forever.start('server.js', { command: 'node' });
```

Relying on the fact that node is in my environment path

**Comment by jiangzhu-genie** [comment]
I have the same problem with 2.0.0, why is this issue closed?

I have my node binary installed in `/Users/jiangzhu/work/Genie/Local Forms Testing/node-macos/bin`
and have a monitor.js script to monitor adapter.js, both in `/Users/jiangzhu/work/Genie/Local Forms Testing/node-macos/dist` folder.

Current working directory is `/Users/jiangzhu/work/Genie/Local Forms Testing/node-macos/dist/adapter`, when I run `../bin/node monitor.js`, I get the error below which caused by incorrect spawnargs

```
Starting monitor for file /Users/jiangzhu/work/Genie/Local Forms Testing/node-macos/dist/adapter.js
events.js:288
      throw er; // Unhandled 'error' event
      ^

Error: spawn /Users/jiangzhu/work/Genie/Local ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn /Users/jiangzhu/work/Genie/Local',
  path: '/Users/jiangzhu/work/Genie/Local',
  spawnargs: [
    'Forms',
    'Testing/node-macos/bin/node',
    '/Users/jiangzhu/work/Genie/Local Forms Testing/node-macos/dist/adapter.js'
  ]
}
```
